sudo: required
#specify docker as a dependency
services:
    - docker
#build test version of react project
before_install:
    - docker build -t vanandaraj0001/react-test -f ./client/Dockerfile.dev ./client
#run test
script:
    - docker run -e CI=true vanandaraj0001/react-test npm test -- --coverage
#build prod version of all projects
after_success:
    - docker build -t vanandaraj0001/multi-client ./client
    - docker build -t vanandaraj0001/multi-nginx ./nginx
    - docker build -t vanandaraj0001/multi-server ./server
    - docker build -t vanandaraj0001/multi-worker ./worker
#login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push all to docker hub
    - docker push vanandaraj0001/multi-client
    - docker push vanandaraj0001/multi-nginx
    - docker push vanandaraj0001/multi-server
    - docker push vanandaraj0001/multi-worker
#tell EB to update